SELECT 
	I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO as I
JOIN (
	SELECT 
		REST_ID, 
		ROUND(AVG(REVIEW_SCORE), 2) as SCORE
	FROM REST_REVIEW
	GROUP BY REST_ID ) as R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS like '서울%'
ORDER BY SCORE desc, FAVORITES desc