-- 코드를 입력하세요
SELECT TITLE, A.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
ON B.BOARD_ID = A.BOARD_ID
WHERE A.CREATED_DATE >= '2022-10-01' AND A.CREATED_DATE < '2022-11-01'
ORDER BY CREATED_DATE, TITLE;